let a = [
  { "Ctrl+X": "Cut line (empty selection)" },
  { "Ctrl+C": "Copy line (empty selection)" },
  { "Alt+Up Arrow/Down Arrow": "Move line up/down" },
  { "Shift+Alt+Down Arrow/Up Arrow": "Copy line up/down" },
  { "Ctrl+Shift+K": "Delete line" },
  { "Ctrl+Enter": "Insert line below" },
  { "Ctrl+Shift+Enter": "Insert line above" },
  { "Ctrl+Shift+ ": "Jump to matching bracket" },
  { "Ctrl+]/[": "Indent/outdent line" },
  { Home: "Go to beginning of line" },
  { End: "Go to End of line" },
  { "Ctrl+Home": "Go to beginning of file" },
  { "Ctrl+End": "Go to End of file" },
  { "Ctrl+Up Arrow/Down Arrow": "Scroll line up/down" },
  { "Alt+PgUp/PgDn": "Scroll page up/down" },
  { "Ctrl+Shift+[": "Fold (collapse) region" },
  { "Ctrl+Shift+]": "Unfold (uncollapse) region" },
  { "Ctrl+K, then Ctrl+[": "Fold (collapse) all subregions" },
  { "Ctrl+K, then Ctrl+]": "Unfold (uncollapse) all subregions" },
  { "Ctrl+K, then Ctrl+0": "Fold (collapse) all regions" },
  { "Ctrl+K, then Ctrl+J": "Unfold (uncollapse) all regions" },
  { "Ctrl+K, then Ctrl+C": "Add line comment" },
  { "Ctrl+K, then Ctrl+U": "Remove line comment" },
  { "Ctrl+/": "Toggle line comment" },
  { "Shift+Alt+A": "Toggle block comment" },
  { "Alt+Z": "Toggle word wrap" },
];
